### PR TITLE
sigma protocols and constant-size damgaard-jurik

### PR DESCRIPTION
**Pull request by meilof**
* sigma protocols:
   -  damgaard-jurik knowledge, product (private multiplie… variant),
   - statistical DH,
   - ElGamal product (private multiplier)
* ability to set fixed size of damgaard-jurik encryptions

### CODE REVIEW

**Comment by meilof** [comment]
See https://github.com/cryptobiu/scapi/pull/43 for more details about the changes.

This pull request additionally contains the ElGamal product proof, but that code is not finished yet: it is not commented well, and the simulator is not complete. So you might want to consider dropping those changes.

**Comment by moriyaw** [comment]
Thanks for helping improve SCAPI!

**Comment by moriyaw** [comment]
Do you have the pseudocode for the El Gamal product sigma protocol? Or a link for a paper describing it?

**Comment by meilof** [comment]
The ElGamal product protocol is quite standard, but you can for instance find it in a recent eprint of ours: https://eprint.iacr.org/2015/339

**Comment by moriyaw** [comment]
Did you check the Sigma protocols you implemented? I have problems with the ElGamal product protocol.
Did you run the protocol and get "verified"?

**Comment by moriyaw** [comment]
Please check the ElGamalProduct and the DamgardJurikProduct2. 
I think there are problems in these protocol, I don't get the expected "verified" result.
Thanks.

**Comment by moriyaw** [comment]
I merged a new branch without the ElGamalProduct and the DamgardJurikProduct2 sigma protocols because the bugs they had. 
In case you manage to fix them, you can add a new pull request and I will be happy to merge it again.
Thanks!

**Pull request merged**
